using System.Collections.Generic;

namespace GameJamSadConsoleSample
{
    public class Intro
    {
        public List<List<string>> intro = new()
        {
            new()
            {
                "  _______________________",
                "/                        \\",
                "|      :-)      :-X      |",
                "\\                       /",
                "  \\____________________/",
                "      |/         \\|",
                "|\\_____/|     ////\\\\",
                "|/// \\\\\\|    /// \\\\\\",
                " |/o O\\|     |/o o\\|",
                " d  o .b     C  )  D",
                "   \\_//      | \\_/ |",
                " __ooo__    _/o|_|o\\_",
                "/_     _\\  / |/\\_/\\| \\",
                "| \\_v_/ | |    |\\|    |",
                "|| _/  _/\\| |  |\\|  | |",
                "||)    ( \\| |  |\\|  | |",
                "||       \\ | \\ |\\|  | |",
                "||  --  |  (())\\_/  | |",
                "((      |   |___|___|_|",
                " |______|   |   Y   |))",
                "  |-||-|    |   |   |",
                "  | || |    |___|___|",
                " /u\\||/u\\   /xx| |xx\\",
                "(_/\\||/\\_) (___/ \\___)",
                "",
                "The poet Patrick William the Third, is sick and tired of this world. Its a turd.",
                "They all speak emoji, he hates that, and doesn't agree.",
                "He wants to get a way, too a place where they appreciate his talent.",
                "Where he can find someone closer to his alignment."
            },
            new()
            {
                "          .-' _____ '-.",
                "        .' .-'.  ':'-. '.",
                "       / .''::: .:    '. \\",
                "      / /   :::::'      \\ \\",
                "     | :.    ':' '       : |",
                "     | |       '..       | |",
                "     | : '      ::::.    : |",
                "      \\ \\       '::::   / /",
                "       \\ '.      :::  .' /",
                "        '. '-.___'_.-' .'",
                "          '-._______.-",
                "             // ",
                "                     ___________________",
                "       .-'''-.       ||    | |         |",
                "      /= ___  \\      ||    | |         |",
                "     |- /---\\  |     ||----'-'---------|",
                "     |=( '.' ) |     ||-----_----------|",
                "     \\__\\_=_/__/     ||    | |         |",
                "      [_______]      ||    | |         |",
                "    /'         ''--._||-----------------",
                "   /= .     [] .     [ >",
                "  /  /|ooo     |''--'|| ",
                " (   )\\_______/      ||",
                "  \\''\\/       \\      ||",
                "",
                "He dreams of another planet, another world, to find his match, who is the greatest catch.",
                "He wants to create his own colony and his own species, that doesnt need prostheses.",
                "How can he find his true love? His bride to be? So that he can finally be free!"
            },
            new()
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "        X                         X",
                "        |                         |",
                "        |                         |",
                "        |                         |",
                "        |                         |",
                "        |                         |",
                "        |                         | ",
                "        |                         |",
                "        |     .==============.    |",
                "   _____|_____||_/########\\_||____|_____",
                "  |(O)____ : [Deep Space] ooooo :___(O)|",
                "  |  /::::\\:  _________  +|+  :/::::\\  |",
                "  |  \\::::/: |    |    | |+|  :\\::::/  |",
                "  |________:_ooooo+==ooo______:________|",
                "",
                "He builds a communications unit, to communicate with his one true love.",
                "His own perfect little dove.",
                "He reaches his love-bird, Patrick William the Third, ",
                "on the planet second closes to the Sun and she sounds like a lot of fun.",
                "She is from Venus and he is from Earth, it will be on Mars she will give birth."
            },
            new()
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "                     '. ___",
                "                    __,' __ '.                _..----....____",
                "        __...--.' ' ':.   ,.   : ' '--..__     .'    ,-._    _.-'",
                "  _..-''-------'    ''    ''    ''     O  ' '-''._   (,:') _,'",
                ",'________________                          \\ '-._ '-','",
                "  '._               ' ' ' ' ' ' ' ' ' ' '------...___   '-.._'-:",
                "     ' ' '--.._      ,.                      ' ' ' '--...__\\-.",
                "             '.--.  '- '      NO WAY           ____    |  | '",
                "               '.  '.                       ,' ' ' ' ' '.  :  : '",
                "                 '._ '.        __________    '.      \'__/ '",
                "                    '-:._____/______/___/____ '.     \\   '",
                "                               |        '._     '.    \\",
                "                               '._________ '-.    '.    '.___",
                "                                                   '------''",
                "",
                "So he build a spaceship out of scraps, and learns how to build it",
                "- on different \"how to-\" apps.",
                "He is smart and eclectic, the spaceship is off course - electric.",
                "However there is a task he most complete, to prove to her, he is not a deadbeat.",
                "He needs to gather some of her lost items from her home planet Venus,",
                "so he can finally show her his solid and erect... gear handle."
            }
        };
    }
}